### ISSUE TITLE
Fail to compile PLC program

### ISSUE THREAD

**Issue by khyarul** [kinsamanka/openplc-stm32-freertos#1]
I've uploaded the bootloader to bluepill board then....
I tried to compile and flash PLC program that already included in directory (plc_prog.st file) using:
`pio run -e bluepill -t upload`

This things happened:

```
Building in release mode
Compiling .pio\build\bluepill\src\generated\POUS.o
src\generated\POUS.c:1:36: error: unknown type name 'TRAFFIC_LIGHT_SEQUENCE'
 void TRAFFIC_LIGHT_SEQUENCE_init__(TRAFFIC_LIGHT_SEQUENCE *data__, BOOL retain) {
                                    ^~~~~~~~~~~~~~~~~~~~~~
src\generated\POUS.c:1:68: error: unknown type name 'BOOL'
 void TRAFFIC_LIGHT_SEQUENCE_init__(TRAFFIC_LIGHT_SEQUENCE *data__, BOOL retain) {
                                                                    ^~~~
src\generated\POUS.c:70:36: error: unknown type name 'TRAFFIC_LIGHT_SEQUENCE'
 void TRAFFIC_LIGHT_SEQUENCE_body__(TRAFFIC_LIGHT_SEQUENCE *data__) {
                                    ^~~~~~~~~~~~~~~~~~~~~~
src\generated\POUS.c:604:22: error: unknown type name 'PROGRAM0'
 void PROGRAM0_init__(PROGRAM0 *data__, BOOL retain) {
                      ^~~~~~~~
src\generated\POUS.c:604:40: error: unknown type name 'BOOL'
 void PROGRAM0_init__(PROGRAM0 *data__, BOOL retain) {
                                        ^~~~
src\generated\POUS.c:623:22: error: unknown type name 'PROGRAM0'
 void PROGRAM0_body__(PROGRAM0 *data__) {
                      ^~~~~~~~
Compiling .pio\build\bluepill\src\plc_task.o
Compiling .pio\build\bluepill\src\tapdev.o
Compiling .pio\build\bluepill\src\uart_task.o
*** [.pio\build\bluepill\src\generated\POUS.o] Error 1
```

Please help
Thank you

**Comment by kinsamanka** [comment]
Try inserting this code below this [line](https://github.com/kinsamanka/openplc-stm32-freertos/blob/0ab06b688de32659c5cc15653e87b6fe40aab145/bin/script.py#L70):

```python
def fix_pous_c(node):
    if "POUS" not in node.name:
        return node

env.AddBuildMiddleware(fix_pous_c)
```

**Comment by khyarul** [comment]
> Try inserting this code below this [line](https://github.com/kinsamanka/openplc-stm32-freertos/blob/0ab06b688de32659c5cc15653e87b6fe40aab145/bin/script.py#L70):
> 
> ```python
> def fix_pous_c(node):
>     if "POUS" not in node.name:
>         return node
> 
> env.AddBuildMiddleware(fix_pous_c)
> ```

It didn't show any error after compile and it starts blinking fast, but when I tried to upload the .st program always failed to init device. The same with my WS214RS module.
`PS C:\Users\MONITA-911\Desktop\openplc-stm32-freertos> pio run -e ws214rs -t upload
Processing ws214rs (board: disco_f030r8; framework: libopencm3; platform: ststm32)
--------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
Compiling plc_prog.st ...
CONFIGURATION: https://docs.platformio.org/page/boards/ststm32/disco_f030r8.html
PLATFORM: ST STM32 (16.1.0) > ST STM32F0308DISCOVERY
HARDWARE: STM32F030R8T6 48MHz, 8KB RAM, 64KB Flash
DEBUG: Current (stlink) On-board (stlink) External (blackmagic, cmsis-dap, jlink)
PACKAGES:
 - framework-libopencm3 @ 1.10000.200730 (1.0.0)
 - tool-dfuutil @ 1.11.0
 - tool-matiec @ 0.1.0+sha.5057635
 - tool-openocd @ 3.1200.0 (12.0)
 - tool-stm32duino @ 1.0.2
 - toolchain-gccarmnoneeabi @ 1.70201.0 (7.2.1)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 4 compatible libraries
Scanning dependencies...
Dependency Graph
|-- freertos
|-- modbus
|-- uip
Building in release mode
Checking size .pio\build\ws214rs\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [========  ]  83.6% (used 6852 bytes from 8192 bytes)
Flash: [==        ]  24.6% (used 16128 bytes from 65536 bytes)
before_upload(["upload"], [".pio\build\ws214rs\firmware.bin"])
Configuring upload protocol...
AVAILABLE: blackmagic, cmsis-dap, jlink, serial, stlink
CURRENT: upload_protocol = serial
Looking for upload port...
Using manually specified: COM10
Uploading .pio\build\ws214rs\firmware.bin
stm32flash 0.4

http://stm32flash.googlecode.com/
Failed to init device.

Using Parser : Raw BINARY
Interface serial_w32: 115200 8E1
*** [upload] Error 1

===================================================== [FAILED] Took 5.21 seconds =====================================================

Environment    Status    Duration
-------------  --------  ------------
ws214rs        FAILED    00:00:05.206
=============================================== 1 failed, 0 succeeded in 00:00:05.206 ===============================================`

**Comment by kinsamanka** [comment]
Is your ws214rs board using stm32f030? (some boards are not).

Where is the log for the bluepill board?

The only thing I can see wrong is the upload speed. It is configured to use 57600 instead of 115200 ([see](https://github.com/kinsamanka/openplc-stm32-freertos/blob/master/platformio.ini#L32-L33)). If you change it, make sure the bootloader code is changed as well.

BTW, I'm not actively developing this one. Have a look [here](https://github.com/kinsamanka/openplc-uploader).

**Comment by khyarul** [comment]
Thank you it's working now
